# Generated by Django 4.0.3 on 2022-03-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(choices=[('U', 'Unseen'), ('Y', 'Like'), ('N', 'Not Like')], default='U', max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, verbose_name='username'),
        ),
    ]
