# Generated by Django 4.0.3 on 2022-03-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_grade_grade_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(choices=[('U', 'Unseen'), ('Y', 'Like'), ('N', 'Not Like')], default='U', max_length=1),
        ),
    ]
