# Generated by Django 4.0.3 on 2022-03-24 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_grade_grade'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('user_id_given', 'user_id_received', 'grade')},
        ),
    ]
