# Generated by Django 4.0.3 on 2022-03-24 18:17

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_grade_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(django.db.models.expressions.F('user_id_given'), django.db.models.expressions.F('user_id_received'), django.db.models.expressions.F('grade'), name='unique_grade'),
        ),
    ]
