# Generated by Django 4.0.3 on 2022-03-23 10:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShikimoriAnimeTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.IntegerField(unique=True, verbose_name='ID тайтла в шикимори')),
            ],
        ),
        migrations.CreateModel(
            name='ShikimoriID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shikiID', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShikimoriTitleRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='shikimori.shikimoriid')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shikimori.shikimorianimetitle')),
            ],
        ),
    ]
